### ISSUE TITLE
Decide on footprints for resistors, capacitors, coils etc

### ISSUE THREAD

**Issue by minatst** [DMPRO-Gruppe-B/Effect-Box-PCB#17]

**Comment by kalkins** [comment]
It's easier to have the same package for all of the same kind of component. It should be a package that is easy to solder by hand. Size doesn't matter that much, we have room

**Comment by HON95** [comment]
Finding electrolytical capacitors and inductors (at DigiKey) with matching footprints is hard ... See Handleliste.
